import Head from "next/head";

import JasonSVG from "../components/JasonSvg";

import { Box } from "@chakra-ui/react";

import useSound from "use-sound";

import Image from "next/image";

export default function Home() {
  const [playCors] = useSound("/cors.mp3");
  return (
    <Box
      bgGradient="linear(to-br, #D459AB, #E79479, #FEDA3C, #B1FCE4 )"
      w="100vw"
      h="100vh"
      d="flex"
      justifyContent="center"
      alignItems="center"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image
        src="/jasonpngfromsvg.png"
        alt="Picture of Jason Legstorf"
        width={200}
        height={250}
        onClick={playCors}
      />
    </Box>
  );
}
